# From original elasticsearch Docker image
network.host: 0.0.0.0

# this value is required because we set "network.host"
# be sure to modify it appropriately for a production cluster deployment
discovery.zen.minimum_master_nodes: 1


# Change from 9200 to 8080, because of Clevercloud
http.port: 8080
